### ISSUE TITLE
Ich kann als Admin nicht meinen Helferlevel ändern

### ISSUE THREAD

**Issue by 5balls** [iridos/Bengelsystem#13]
Ich kann meinen eigenen Helferlevel (und den von anderen) nicht ändern, obwohl ich Admin bin. Könnte so gewollt sein, dann ist es "enhancement" oder sogar kein issue, sonst "bug" ;)

**Comment by iridos** [comment]
Helferlevel ändern ist jetzt als Admin möglich. War vielleicht weniger "bug" als "noch nicht fertig implementiert".
wurde in helferlevel-aendern-und-anzeige-level-in-helferuebersicht geändert.
