### ISSUE TITLE
Kalenderstartdatum wird noch nicht richtig aus der konfig.php übernommen für Adminkalender

### ISSUE THREAD

**Issue by 5balls** [iridos/Bengelsystem#14]
Ich weiß Karsten ist schon dran, nur das wir es auf dem Schirm haben.

**Comment by iridos** [comment]
Auch in https://github.com/iridos/Bengelsystem/tree/15-kalender-wird-f%C3%BCr-normale-benutzer-gar-nicht-angezeigt erledigt ich kann den Zweig aber hier nicht dranlinken.
